POST http://localhost:8080/api/courier
Content-Type: application/json

{
  "creatingUserId": 1,
  "modifyingUserId": 4,
  "firstName": "Zoltán",
  "lastName": "Kis",
  "phoneNumber": "+36/30 123-4567"
}

###

PUT http://localhost:8080/api/courier
Content-Type: application/json

{
  "id": 12,
  "creatingUserId": 4,
  "modifyingUserId": 4,
  "firstName": "Zoltáns",
  "lastName": "Kiss",
  "phoneNumber": "+36/30 123-1234"
}

###
GET http://localhost:8080/api/courier
Accept: application/json

###

DELETE http://localhost:8080/api/courier/13
Accept: application/json

###


###

GET http://localhost:8080/api/courier/13
Accept: application/json

###