POST http://localhost:8080/api/order
Content-Type: application/json

{
  "creatingUserId": 1,
  "modifyingUserId": 2,
  "courierId": 1,
  "settlement": "Bököny",
  "publicSpace": "Kossuth",
  "publicSpaceNature": "utca",
  "houseNumber": 100
}

###

PUT http://localhost:8080/api/order
Content-Type: application/json

{
  "id": 2,
  "creatingUserId": 1,
  "modifyingUserId": 2,
  "courierId": 1,
  "foodListId": 1,
  "settlement": "Bököny",
  "publicSpace": "Kossuth",
  "publicSpaceNature": "utca",
  "houseNumber": 100
}

###
GET http://localhost:8080/api/order
Accept: application/json

###

DELETE http://localhost:8080/api/order/8
Accept: application/json

###


###

GET http://localhost:8080/api/order/16
Accept: application/json

###