POST http://localhost:8080/api/order
Content-Type: application/json

{
  "creatingUserId": 4,
  "deliveryDate" : "2021.08.29 21:03:30",
  "courierId": 12,
  "settlement": "Bököny",
  "publicSpace": "Kossuth",
  "publicSpaceNature": "utca",
  "houseNumber": 100
}

###

PUT http://localhost:8080/api/order
Content-Type: application/json

{
  "id": 25,
  "deliveryDate" : "2021.08.30 21:03:30",
  "creatingUserId": 4,
  "modifyingUserId": 2,
  "courierId": 1,
  "settlement": "Bököny",
  "publicSpace": "Kossuth",
  "publicSpaceNature": "utca",
  "houseNumber": 1000
}

###
GET http://localhost:8080/api/order
Accept: application/json

###

DELETE http://localhost:8080/api/order/25
Accept: application/json

###


###

GET http://localhost:8080/api/order/25
Accept: application/json

###